site_name: Úvod do statistické analýzy
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: deep orange
    accent: amber
    
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
    - callouts

nav:
    - 'index.md'
    - 'kombinatorika.md'
    - 'teorie_pravdepodobnosti.md'
    - 'diskretni_rozdeleni.md'
    - 'spojita_rozdeleni.md'
    - 'vyberove_charakteristiky.md'

markdown_extensions:
    - mdx_math
    - admonition
    - pymdownx.details
    - pymdownx.superfences